name: macos

on: [push, pull_request]

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code -fsanitize=address -fsanitize=undefined"

jobs:
  # Build PICSAR tests, PICSAR python bindings, and Kokkos examples
  tutorials-macos:
    name: QED with tests, python bindings, Kokkos examples
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Test
      run: |
        cmake -S multi_physics/QED                \
            -B build                              \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DPXRMP_QED_TEST=ON                   \
            -DPXRMP_KOKKOS_EXAMPLE=ON             \
            -DKokkos_ENABLE_OPENMP=ON             \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
        cmake --build build -j 2
        ctest --test-dir build --output-on-failure
